---
dist: bionic
language: python

cache: pip

git:
  depth: 100

jobs:
  fast_finish: true

  include:
  - python: 3.7
    name: Running linters
    script:
    - flake8

  - python: 3.8
    before_install:
    - pip install distro

  - python: 3.7

  - python: 3.6

  - python: 3.5

  - python: 2.7

  - language: generic
    name: Running hadolint
    sudo: false
    env: 
      HADOLINT: "${HOME}/hadolint"
    install:
      # Download hadolint binary and set it as executable
      - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.16.0/hadolint-$(uname -s)-$(uname -m)"
        && chmod 700 ${HADOLINT}
    script:
      # List files which name starts with 'Dockerfile'
      # eg. Dockerfile, Dockerfile.build, etc.
      - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}

  - python: 3.7
    stage: Deploy
    name: Publishing current Git tagged version of dist to PyPI
    if: repo == "warpnet/salt-lint" AND tag IS present AND branch == "master" AND type NOT IN (cron, pull_request)
    before_install: []
    # Deploy a new release to PyPi for every new tag on the 'master' branch on the
    # repository 'warpnet/salt-lint'.
    deploy:
      provider: pypi
      user: __token__
      password:
        # A PyPI API token can be generated by a PyPi maintainer on:
        #  https://pypi.org/help/#apitoken
        # The API token in encrypted using `travis encrypt api-token`.
        secure: "fL3/pkTaRA+cmTdC5Qxo9xoDoxXv6VbwbT3fM5JwW1F0NPbqR7Kw+oMJl2ZKQZrbRxvtPps8dYzxqC0axZ+WRFeVz+FzFeosziU/1kk1U5Bks5VK1my0kPl9jlD1kM0gS8mSm6gdNHJ6Z8quEXuYCMtMhqyCMgw0PWRaMOuuQ5Yi6/olUPjDxkMsFeh+03VIXTXGHPk7GxR3OTbOUaIaQXkbt7RQ7usDHnd1W6jeW5a1Q2h2cvugHfk6B9UYaXnIacCSejD4NJHkE+j3lbVI6QuzBO3MdaEM6V/+P3zDh0ZF9SK2BfXdNqMtCij/u8q0er+Y6ZU1LGDrRuXe6bmRr6KyJfiOsgKOCyLXSNqGGim01eJHO14DUgGrc8qWo1KKywtxagIriMcTxAOccW8RDRy3zkKYdEHgdFs6MtVL2JV+wyhdxxoU6DOZsNn6N8d9WninpAcIPtfiYzBRerQqR0OiKmpDK4Oee9IKCfRhMhWAY7Rs/RV33YluEJbv4bWPcPMPciEUp/xXxwPMWFQ45VoR4ZiwBYz0KoOMb/QrVfN8m8pdEtQpSUX51PFTFzmrreB6OvwJ5aphMrxIpvCJNZ65mfZthDKJUhSo0EG6ix/g4nOR7qlLNMVsQF4qSRCKDJlqUlzXYpQuy0u/QXoihCReO5rI6nWdV/KTfHCYgdo="
      on:
        repo: warpnet/salt-lint
        tags: true
        branch: master
        python: 3.7

install:
  - pip install -r test-deps.txt
  - pip install .

script:
  - coverage run --source=saltlint setup.py test
  - coveralls
